#!/bin/bash
set -e

resources=/Volumes/Regina/Regina.app/Contents/Resources
large=/Users/bab/git/regina-aux/data/census

if [ ! -f buildtips.html ]; then
  echo "ERROR: This script must be run from within the root directory"
  echo "       of the website repository."
  exit 1
fi

if [ ! -d "$resources/examples" ]; then
  echo "ERROR: The macOS app bundle must be mounted as /Volumes/Regina/."
  exit 2
fi

rm -rf census docs engine-docs

cp -pr "$resources/examples" census
cp -pf "$large"/*.rga census
cp -pr "$resources/docs/en/regina" docs
cp -pr "$resources/engine-docs" .

echo "Done."
