#!/bin/bash
set -e

function requires {
  if [ ! -d "$1" ]; then
    echo "ERROR: Missing directory $1."
    exit 1
  fi
  if [ ! -e "$1/$2" ]; then
    echo "ERROR: Missing file $1/$2."
    exit 1
  fi
}

requires ios regina-doc-64.png
mv ios/regina-doc-*.png ~/git/regina/ios

requires ios regina-310.png
requires ios regina-310@2x.png
requires ios regina-310@3x.png
mv ios/regina-310{,@2x,@3x}.png ~/git/regina/ios/Images.xcassets/ReginaLarge.imageset

requires ios regina-32.png
requires ios regina-32@2x.png
requires ios regina-32@3x.png
mv ios/regina-32{,@2x,@3x}.png ~/git/regina/ios/Images.xcassets/Packets/Document.imageset

requires ios app-64.png
requires ios app-80-1.png
mv ios/app*.png ~/git/regina/ios/Images.xcassets/AppIcon.appiconset
