#!/bin/bash
set -e

# OSX icons:
rm -rf regina.iconset x-regina.iconset
mkdir regina.iconset x-regina.iconset
for i in 16 32 128 256 512; do
  size=$i
  rsvg -w$size -h$size regina.svg regina.iconset/icon_${size}x${size}.png
  rsvg -w$size -h$size x-regina.svg x-regina.iconset/icon_${size}x${size}.png
  size=$(($i + $i))
  rsvg -w$size -h$size regina.svg regina.iconset/icon_${i}x${i}@2x.png
  rsvg -w$size -h$size x-regina.svg x-regina.iconset/icon_${i}x${i}@2x.png
done
xcrun iconutil -c icns regina.iconset
xcrun iconutil -c icns x-regina.iconset
rm -rf regina.iconset x-regina.iconset

# MSWindows icons (regina, x-regina): TODO

# XDG icons:
rm -rf xdg
mkdir xdg
for i in 16 22 24 32 48 64 128 256; do
  size=$i
  rsvg -w$size -h$size regina.svg xdg/regina-${size}.png
  rsvg -w$size -h$size x-regina.svg xdg/x-regina-${size}.png
done

# QtUI icons:
rm -rf qtui
mkdir qtui
for i in 16 22 32 48 64; do
  size=$i
  rsvg -w$size -h$size regina.svg qtui/regina-${i}.png
  size=$(($i + $i))
  rsvg -w$size -h$size regina.svg qtui/regina-${i}@2x.png
done

# iOS icons:
# - ReginaLarge: 310 (x1,2,3)
# - Packets/Document: 32 (x1,2,3)
# - RGA DocType: 64 320
rm -rf ios
mkdir ios
for i in 32 310; do
  size=$i
  rsvg -w$size -h$size regina.svg ios/regina-${i}.png
  size=$(($i+$i))
  rsvg -w$size -h$size regina.svg ios/regina-${i}@2x.png
  size=$(($i+$i+$i))
  rsvg -w$size -h$size regina.svg ios/regina-${i}@3x.png
done
for i in 64 320; do
  size=$i
  rsvg -w$size -h$size regina.svg ios/regina-doc-${size}.png
done

