#!/bin/bash
set -e

# Transparent:
#
# - ReginaLarge: 310 620 930
# - Packets/Document: 32 64 96
# - RGA DocType: 64 320
# - QtUI: 16 22 32

for i in 16 22 32 64 96 310 320 620 930; do
  convert -geometry ${i}x${i} regina.png regina-$i.png
done

# Background:
#
# - App icon: 16 32 64 128 256 512 1024
# - Spotlight: 40 80
# - Settings: 29 58
# - iPad app: 76 152
# - iPhone app: 120 180

for i in 16 29 32 40 58 64 76 80 120 128 152 180 256 512 1024; do
  convert -geometry ${i}x${i} regina-bg.png regina-bg-$i.png
done
