#!/bin/bash
set -e

if [ -d regina ]; then
  # Purge anything outside the regina subdirectory.
  rm -rf CVSROOT data icons packaging www
  files=`ls -a`
  for i in $files; do
    case "$i" in
      . ) ;;
      .. ) ;;
      .git ) ;;
      regina ) ;;
      * )
        echo "ERROR: Unexpected top-level file/directory: $i"
        exit 1
    esac
  done

  # Move everything up from within the regina subdirectory.
  shopt -s dotglob nullglob
  mv regina tmp-regina
  mv tmp-regina/* .
  if (! rmdir tmp-regina); then
    echo "ERROR: Could not remove subdirectory"
    ls -a tmp-regina
    exit 1
  fi
elif [ -d CVSROOT ]; then
  # An initial commit, before the source tree was added.
  # Make this an empty directory tree.
  rm -rf CVSROOT
  files=`ls -a`
  for i in $files; do
    case "$i" in
      . ) ;;
      .. ) ;;
      .git ) ;;
      * )
        echo "ERROR: Unexpected top-level file/directory: $i"
        exit 1
    esac
  done
fi
