#!/bin/bash
set -e

if [ -d regina -o -d CVSROOT ]; then
  # We are at the top level.
  # Kill off the regina subdirectory and keep everything else.
  rm -rf regina
else
  # We are inside the regina subdirectory.
  # Kill off everything.
  rm -rf *
  files=`ls -a`
  for i in $files; do
    case "$i" in
      . ) ;;
      .. ) ;;
      .git ) ;;
      .cvsignore )
        rm "$i" ;;
      * )
        echo "ERROR: Unexpected top-level file/directory: $i"
        exit 1
    esac
  done
fi
