#!/bin/bash
#
# Note: on fink this requires librsvg2-bin.
#
set -e

for i in "$@"; do
  case "$i" in
    *) sizes="22 44 66";;
  esac
  for j in $sizes; do
    rsvg -w$j -h$j $i.svg $i-$j.png
  done
done
