#!/bin/bash
#
# Note: on fink this requires librsvg2-bin.
#
set -e

for i in "$@"; do
  case "$i" in
    # graph* ) sizes="30 60 90";;
    *) sizes="25 50 75";;
  esac
  for j in $sizes; do
    rsvg -w$j -h$j $i.svg $i-$j.png
  done
done
