#!/bin/bash
set -e

if [ ! -f buildtips.html ]; then
  echo "ERROR: This script must be run from within the www/ directory."
  exit 1
fi

cd ..
rm -rf staging

cp -pr www staging

chmod -R a+r staging

tar -zcf staging.tgz staging
rm -rf staging

echo "The tarball is waiting for you in ../staging.tgz."
