#!/bin/bash
#
# Note: on fink this requires librsvg2-bin.
#
set -e

for i in "$@"; do
  for j in 16 22 32; do
    size=$j
    if [ "$j" = 16 -a -e "$i-lores.svg" ]; then
      echo "16px: using lo-res SVG"
      rsvg -w$size -h$size $i-lores.svg $i-$size.png
    else
      rsvg -w$size -h$size $i.svg $i-$size.png
    fi
    size=$(($j + $j))
    rsvg -w$size -h$size $i.svg $i-$j@2x.png
    size=$(($size + $j))
    rsvg -w$size -h$size $i.svg $i-$j@3x.png
  done
done
