#!/bin/bash
set -e

allow64=`sysctl -n hw.optional.x86_64`
if [ "x$allow64" != "x1" ]; then
  echo '32-bit builds are no longer supported.'
  exit 1
fi

# Extract the default python version on MacOS and rewrite it as a
# version-specific pythonX.Y, so newer platforms will use the same
# (older) version against which it was built.
pyver=`/usr/bin/python --version 2>&1 | cut -d' ' -f2`
pymaj=`echo "$pyver" | cut -d. -f1`
pymin=`echo "$pyver" | cut -d. -f2`
pybin=/usr/bin/python$pymaj.$pymin
if [ "$pybin" = /usr/bin/python ]; then
  echo "Could not detect version-specific python binary"
  exit 1
fi
if [ ! -e "$pybin" ]; then
  echo "Broken python: $pybin"
  exit 1
fi

mkdir build
cd build

DEST=/Users/bab
rm -rf "$DEST/Regina.app"

cmake \
  -DCMAKE_INSTALL_PREFIX="$DEST" \
  -DPYTHON_EXECUTABLE="$pybin" \
  -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake \
  -DPACKAGING_MODE=1 \
  -DDISABLE_MPI=1 \
  ..

make
make test ARGS=-V
make install

echo 'Adding missing Info.plist files to Qt for code signing...'
for i in QtCore QtGui; do
  cp -v /Library/Frameworks/$i.framework/Contents/Info.plist \
    "$DEST/Regina.app/Contents/Frameworks/$i.framework/Resources/"
done

