#!/bin/bash
set -e

allow64=`sysctl -n hw.optional.x86_64`
if [ "x$allow64" != "x1" ]; then
  echo '32-bit builds are no longer supported.'
  exit 1
fi

# Make sure we have uninstalled libxml2 and libiconv-dev, so that we
# pick up Apple's versions of these.
for pkg in libxml2 libiconv-dev; do
  if ! (apt-cache policy "$pkg" | grep Installed:..none > /dev/null); then
    echo "Please uninstall the fink package $pkg."
    exit 1
  fi
done

# Extract the default python version on MacOS and rewrite it as a
# version-specific pythonX.Y, so newer platforms will use the same
# (older) version against which it was built.
pyver=`/usr/bin/python --version 2>&1 | cut -d' ' -f2`
pymaj=`echo "$pyver" | cut -d. -f1`
pymin=`echo "$pyver" | cut -d. -f2`
pybin=/usr/bin/python$pymaj.$pymin
if [ "$pybin" = /usr/bin/python ]; then
  echo "Could not detect version-specific python binary"
  exit 1
fi
if [ ! -e "$pybin" ]; then
  echo "Broken python: $pybin"
  exit 1
fi

if [ -d build ]; then
  echo "Please remove the build/ subdirectory and try again."
  exit 1
fi
mkdir build
cd build

DEST=/Users/bab
rm -rf "$DEST/Regina.app"

cmake \
  -DCMAKE_INSTALL_PREFIX="$DEST" \
  -DPYTHON_EXECUTABLE="$pybin" \
  -DCMAKE_PREFIX_PATH=/Users/bab/Qt5/5.3/clang_64 \
  -DPACKAGING_MODE=1 \
  -DDISABLE_MPI=1 \
  ..

make
make test ARGS=-V
make install

# Clean up the Qt bundles, which are not laid out correctly.
for i in QtCore QtGui QtWidgets QtSvg; do
  fwdir="$DEST/Regina.app/Contents/Frameworks/$i.framework"
  resdir="$fwdir/Versions/5/Resources"

  if [ -e "$resdir" ]; then
    echo "ERROR: versioned Resources directory already exists."
    exit 1
  fi
  if [ -d "$fwdir/Resources" ]; then
    echo "$i: moving Resources/ into versioned framework directory..."
    mv "$fwdir/Resources" "$resdir"
  else
    echo "$i: creating versioned Resources directory..."
    mkdir "$resdir"
  fi

  echo "$i: adding missing Info.plist file to framework..."
  cp ~/Qt5/5.3/clang_64/lib/$i.framework/Contents/Info.plist "$resdir"

  if [ -e "$fwdir/Versions/Current" ]; then
    echo "ERROR: Current symlink already exists."
    exit 1
  fi

  echo "$i: setting up symlinks..."
  ( cd "$fwdir/Versions" ; ln -s 5 Current )
  ( cd "$fwdir" ; ln -s Versions/Current/Resources Resources )
done

