#!/bin/bash
set -e

app="$1"
if ! [ -e "$1/Contents/MacOS/Regina" ]; then
  echo "Usage: sign-all path/to/Regina.app"
  exit 1
fi

echo 'Signing frameworks...'
codesign -s 'Developer ID' -v "$app"/Contents/Frameworks/*.framework
echo

echo 'Signing dylibs...'
# Don't try to sign libregina-engine.dylib (the symlink), since this
# will break with an already-signed error.
codesign -s 'Developer ID' -v "$app"/Contents/MacOS/lib{boost*,*.*}.dylib
echo

echo 'Signing python module...'
codesign -s 'Developer ID' -v "$app"/Contents/MacOS/python/regina/*
echo

echo 'Signing standalone executables...'
codesign -s 'Developer ID' -v "$app"/Contents/MacOS/{census*,reg*,sig*,tri*}
echo

echo 'Signing app bundle...'
codesign -s 'Developer ID' -v "$app"

