#!/bin/bash
#
# Note: on fink this requires librsvg2-bin.
#
set -e

function render {
    src=$1
    size=$2
    filename=$3

    if [ "$size" = 16 -a -e "$src-lores.svg" ]; then
      echo "$filename: using lo-res SVG"
      rsvg -w$size -h$size $src-lores.svg $filename
    elif [ -e "$src-$size.svg" ]; then
      echo "$filename: using ${size}x SVG"
      rsvg -w$size -h$size $src-$size.svg $filename
    else
      rsvg -w$size -h$size $src.svg $filename
    fi
}

for i in "$@"; do
  for j in 16 22 32; do
    render $i $j $i-$j.png
    render $i $(($j+$j)) $i-$j@2x.png
    render $i $(($j+$j+$j)) $i-$j@3x.png
  done
done
